"""Named defaults shared across the semantic reconstruction pipeline."""

HEADING_CANDIDATE_MIN_SCORE = 0.18
HEADING_PROMOTION_MIN_SCORE = 0.42
MAJOR_HEADING_CONFIDENCE = 0.68
LLM_REVIEW_CONFIDENCE_THRESHOLD = 0.72
KNOWN_SECTION_CONFIDENCE = 0.82
SECTION_REASONING_APPLY_CONFIDENCE = 0.82
SECTION_REASONING_ADOPT_CONFIDENCE = 0.86
TOC_MATCH_CONFIDENCE = 0.92

